"""empty message

Revision ID: 0c0840a925d1
Revises: e38f6a1ce90b
Create Date: 2021-10-22 20:20:49.079734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0840a925d1'
down_revision = 'e38f6a1ce90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favoriteCharacter_ibfk_1', 'favoriteCharacter', type_='foreignkey')
    op.create_foreign_key(None, 'favoriteCharacter', 'character', ['character_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoriteCharacter', type_='foreignkey')
    op.create_foreign_key('favoriteCharacter_ibfk_1', 'favoriteCharacter', 'character', ['character_id'], ['id'])
    # ### end Alembic commands ###
