"""empty message

Revision ID: 1d0da073b374
Revises: 0c0840a925d1
Create Date: 2021-10-22 20:22:30.964652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0da073b374'
down_revision = '0c0840a925d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FavoriteVehicle_ibfk_2', 'FavoriteVehicle', type_='foreignkey')
    op.create_foreign_key(None, 'FavoriteVehicle', 'vehicle', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('favoritePlanet_ibfk_1', 'favoritePlanet', type_='foreignkey')
    op.create_foreign_key(None, 'favoritePlanet', 'planet', ['planet_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoritePlanet', type_='foreignkey')
    op.create_foreign_key('favoritePlanet_ibfk_1', 'favoritePlanet', 'planet', ['planet_id'], ['id'])
    op.drop_constraint(None, 'FavoriteVehicle', type_='foreignkey')
    op.create_foreign_key('FavoriteVehicle_ibfk_2', 'FavoriteVehicle', 'vehicle', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###
