"""empty message

Revision ID: 6a060747730b
Revises: f1a441bed57b
Create Date: 2021-10-21 20:29:33.100416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a060747730b'
down_revision = 'f1a441bed57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fav_character_id', sa.Integer(), nullable=True),
    sa.Column('fav_planet_id', sa.Integer(), nullable=True),
    sa.Column('fav_vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fav_character_id'], ['favoriteCharacter.id'], ),
    sa.ForeignKeyConstraint(['fav_planet_id'], ['favoritePlanet.id'], ),
    sa.ForeignKeyConstraint(['fav_vehicle_id'], ['FavoriteVehicle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
