"""empty message

Revision ID: 8fbff6a7d4c1
Revises: 865525c123e9
Create Date: 2021-10-24 00:48:07.006609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbff6a7d4c1'
down_revision = '865525c123e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FavoriteVehicle_ibfk_1', 'FavoriteVehicle', type_='foreignkey')
    op.create_foreign_key(None, 'FavoriteVehicle', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('favoritePlanet_ibfk_2', 'favoritePlanet', type_='foreignkey')
    op.create_foreign_key(None, 'favoritePlanet', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoritePlanet', type_='foreignkey')
    op.create_foreign_key('favoritePlanet_ibfk_2', 'favoritePlanet', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'FavoriteVehicle', type_='foreignkey')
    op.create_foreign_key('FavoriteVehicle_ibfk_1', 'FavoriteVehicle', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
