"""empty message

Revision ID: a7f2a7ecb2d3
Revises: 43ee4b70b07a
Create Date: 2021-10-25 23:39:06.072149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7f2a7ecb2d3'
down_revision = '43ee4b70b07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'hair_color',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('character', 'eye_color',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('character', 'birth_year',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('character', 'height',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'population',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('vehicle', 'cost_in_credits',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('vehicle', 'passengers',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'passengers',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('vehicle', 'cost_in_credits',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'population',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('character', 'height',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('character', 'birth_year',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('character', 'eye_color',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('character', 'hair_color',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
